sudo: false
language: python
dist: trusty

jobs:
  fast_finish: true
  include:

    - stage: Linux - Conan Current
      name: Python 3.6
      python: 3.6
      env: TOXENV=py36-conan
      dist: xenial

install:
  - pip install --upgrade pip
  - pip install tox tox-venv tox-travis

script:
  - tox
